### ISSUE TITLE
Sensitive config should not be baked-in to YML files and VCS

### ISSUE THREAD

**Issue by dcentrica** [Level51/silverstripe-jwt-utils#5]
Library users should be able to consume config from environment variables via Silverstripe's config system instead of having authentication secrets saved to YML files and committed to VCS.

Working like this also makes working with containers easy because config can be set via ENV vars in CI pipelines and at image build time:

From:
```yml
Level51\JWTUtils\JWTUtils:
  secret: "k4tfud."
```
```php
private function hasValidSecret() {
    return boolval(Config::inst()->get(self::class, 'secret'));
}
```

TO:
```yml
Level51\JWTUtils\JWTUtils:
  secret: "`JWT_SECRET_FROM_ENV`"
```
```
private function hasValidSecret()
{
    return boolval(Injector::inst()->convertServiceProperty(Config::inst()->get(self::class, 'secret')));
}
```

**Comment by JZubero** [comment]
Agreeing that sensitive data should not be included in versioned files. Since "[Environment variables cannot be used outside of Injector config as of version 4.2.](https://docs.silverstripe.org/en/4/getting_started/environment_management/#using-environment-variables-in-config)", I was wondering if you are suggesting the use of `Injector::inst()->convertServiceProperty()` to overcome this?
